#!/bin/sh

set -eu

borgmatic init -e repokey-blake2

for zone in $(flarectl --json zone list | jq -r '.[].Name'); do
    flarectl zone export --zone="$zone" >"$zone.txt"
done

borgmatic -v"${VERBOSITY:-1}" --stats
