#!/bin/sh

set -eux

borgmatic init -e repokey-blake2

zones="$(flarectl --json zone list | jq -r '.[].Name')"
moreutils parallel sh -c 'flarectl zone export --zone="$0" > "$0.txt"' -- $zones

borgmatic -v"${VERBOSITY:-1}" --stats
